steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - "-c"
      - |
        gcloud compute ssh moodle-vm \
          --zone=us-central1-a \
          --command="cd /home/a_videnov8a/TU_ST_project && git pull origin master && sudo systemctl restart apache2 && echo 'bruh'"
    entrypoint: bash

options:
  logging: CLOUD_LOGGING_ONLY
